### ISSUE TITLE
Direct access to socket handles

### ISSUE THREAD

**Issue by rektide** [rubenv/node-systemd#2]
Hello,

I would like direct access to individual socket handles passed in to my program.

At present, this library does not expose sockets: it monkeypatches net's Server.listen call. I would prefer a library which also exposes the ability to iterate through all sockets passed by systemd socket activation.

**Comment by rubenv** [comment]
Hi, as I'm no longer able to maintain this package, I'll be archiving this repo. I recommend looking into one of the forks, such as [@derhuerst/systemd](https://github.com/derhuerst/node-systemd).
