### ISSUE TITLE
request.connection.remoteAddress is undefined

### ISSUE THREAD

**Issue by timbertson** [rubenv/node-systemd#8]
In a normal (non-systemd) server, `request.connection.remoteAddress` is the recommended way to get the IP address of the client.

Since node-systemd wraps up the FD as a pipe (and not a TCP socket), its _getpeername method is not implemented, so `connection.remoteAddress` always returns undefined.

There's a bit of (slightly old) information about this problem here: http://benno.id.au/blog/2012/12/08/node-prebound-sockets. The APIs mentioned are all most likely out of date, but the general problem still seems the same. Any ideas on how to fix this? Or workarounds for accessing the client IP?

**Comment by RAnders00** [comment]
Sorry for reviving this ancient conversation, but I've encountered a use case where using nginx to add the header is not possible. I'm building a FTP server which cannot be proxied using nginx. I can also reproduce that `remoteAddress` and `remotePort` are `undefined`. Any chance this can get fixed?

**Comment by rubenv** [comment]
Hi, as I'm no longer able to maintain this package, I'll be archiving this repo. I recommend looking into one of the forks, such as [@derhuerst/systemd](https://github.com/derhuerst/node-systemd).
